spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/englishwordstest?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ewt
    password: english!words@test#
  jpa:
    hibernate:
      ddl-auto: none